version: '3.8'

services:
  frontend:
    container_name: Shubham-Tamboli
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
